"""add_exam_attempt_models

Revision ID: 1ab8aa4cf881
Revises: eae47ecbe8f2
Create Date: 2026-08-08 09:18:03.364234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ab8aa4cf881'
down_revision: Union[str, Sequence[str], None] = 'eae47ecbe8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exam_attempts_exam_user', 'exam_attempts', ['exam_id', 'user_id'], unique=False)
    op.create_index('idx_exam_attempts_status', 'exam_attempts', ['status'], unique=False)

    op.create_table('exam_attempt_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('selected_answer', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exam_attempt_answers_attempt_question', 'exam_attempt_answers', ['attempt_id', 'question_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_exam_attempt_answers_attempt_question', table_name='exam_attempt_answers')
    op.drop_table('exam_attempt_answers')
    op.drop_index('idx_exam_attempts_status', table_name='exam_attempts')
    op.drop_index('idx_exam_attempts_exam_user', table_name='exam_attempts')
    op.drop_table('exam_attempts')
    # ### end Alembic commands ###
