"""initial exam service

Revision ID: eae47ecbe8f2
Revises: 
Create Date: 2026-08-08 02:26:13.678888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae47ecbe8f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=True),
    sa.Column('shuffle_options', sa.Boolean(), nullable=True),
    sa.Column('show_result_after_submit', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exams_created_by', 'exams', ['created_by'], unique=False)
    op.create_index('idx_exams_status', 'exams', ['status'], unique=False)
    op.create_table('exam_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exam_assignments_teacher_id', 'exam_assignments', ['teacher_id'], unique=False)
    op.create_table('exam_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=True),
    sa.Column('point_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exam_questions_exam_id', 'exam_questions', ['exam_id'], unique=False)
    op.create_table('exam_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exam_schedules_end_time', 'exam_schedules', ['end_time'], unique=False)
    op.create_index('idx_exam_schedules_start_time', 'exam_schedules', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_exam_schedules_start_time', table_name='exam_schedules')
    op.drop_index('idx_exam_schedules_end_time', table_name='exam_schedules')
    op.drop_table('exam_schedules')
    op.drop_index('idx_exam_questions_exam_id', table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_index('idx_exam_assignments_teacher_id', table_name='exam_assignments')
    op.drop_table('exam_assignments')
    op.drop_index('idx_exams_status', table_name='exams')
    op.drop_index('idx_exams_created_by', table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
